# Generated by Django 4.2.2 on 2023-11-28 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_name', models.CharField(choices=[('ac', 'A/C'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine')], default='ac', max_length=100)),
                ('inverter', models.BooleanField(default=False)),
                ('fully_automatic', models.BooleanField(default=False)),
                ('next_service_date', models.DateField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliance_name', models.CharField(choices=[('ac', 'A/C'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine')], default='ac', max_length=100, verbose_name='Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='CommonComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.CharField(choices=[('ac', 'A/C'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine')], default='ac', max_length=100)),
                ('complaint', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('appliance', 'complaint')},
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=60)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('appliance_name', models.CharField(choices=[('ac', 'A/C'), ('refrigerator', 'Refrigerator'), ('washing_machine', 'Washing Machine')], default='ac', max_length=100, verbose_name='Appliance')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('new', 'New'), ('rework', 'Re-work')], default='new', max_length=60)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parts_pending', 'parts_pending'), ('completed', 'Completed')], default='pending', max_length=60)),
                ('rectified_date', models.DateField(blank=True, null=True)),
                ('rectified_issue', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bill_amt', models.CharField(blank=True, max_length=60, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycool.appliances')),
                ('common_complaint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycool.commoncomplaints', verbose_name='complaint')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycool.customers')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=models.SET('technician_deleted'), to='easycool.technicians')),
            ],
        ),
        migrations.AddField(
            model_name='appliances',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='easycool.brands'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='easycool.capacity'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='easycool.customers'),
        ),
        migrations.AddField(
            model_name='appliances',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='easycool.types'),
        ),
    ]
