# Generated by Django 4.2.2 on 2023-11-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easycool', '0002_appliances_mail_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliances',
            name='mail_sent_date',
        ),
    ]
